### ISSUE TITLE
Namespace XHP code

### ISSUE THREAD

**Issue by jacobconley** [jacobconley/catarini-hhvm#16]
Apparently this is allowed now

https://github.com/hhvm/xhp-lib/issues/64

Maybe put all this shite in render?

**Comment by jacobconley** [comment]
Still messes up tag names; closing

**Comment by fredemmott** [comment]
It was supported if certain typechecker and options were enabled; with xhp-lib v4 and HHVM/Hack 4.73, it works well. https://hhvm.com/blog/2020/09/02/XHP-namespaces-and-syntax.html
